torso_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - torso_lift_joint

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 5.0 # FIXME: See #8429
    torso_lift_joint:
      goal: 0.02

head_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - head_1_joint
    - head_2_joint

  constraints:
    goal_time: 2.0
    stopped_velocity_tolerance: 5.0
    head_1_joint:
      goal: 0.02
    head_2_joint:
      goal: 0.02

arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - arm_1_joint
    - arm_2_joint
    - arm_3_joint
    - arm_4_joint
    - arm_5_joint
    - arm_6_joint
    - arm_7_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 5.0
    arm_1_joint:
      goal: 0.025
    arm_2_joint:
      goal: 0.025
    arm_3_joint:
      goal: 0.025
    arm_4_joint:
      goal: 0.025
    arm_5_joint:
      goal: 0.025
    arm_6_joint:
      goal: 0.025
    arm_7_joint:
      goal: 0.025
